name: Frontend CI & Deploy

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
  
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 9
  
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: 'pnpm'
  
        - name: Install Dependencies
          run: pnpm install
  
        - name: Check Code Quality (Lint)
          run: pnpm lint
  
        - name: Try Building Project
          run: pnpm build
  
    deploy:
      if: github.event_name == 'push'
      needs: build-and-test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
  
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 9
  
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
  
        - name: Install Dependencies
          run: pnpm install
  
        - name: Build
          run: pnpm build
  
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./dist  # اگر خروجی build شما در پوشه دیگریست (مثلا ./build) این را عوض کنید
